blank_issues_enabled: false
contact_links:
  - name: Want to Discuss something?
    url: https://github.com/JAYAROSHINI2112/All_Rounder/discussions/2
    about: For any Discussion, Query.
  - name: Guidelines
    url: https://github.com/JAYAROSHINI2112/All_Rounder/blob/main/CONTRIBUTING.md
    about: Our contribution guidelines (Please go through them).
